# Generated by Django 4.2.6 on 2023-10-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='thread',
            name='topico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topico', to='main.topico'),
        ),
    ]
