# Generated by Django 4.2.5 on 2023-10-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_topico_alter_user_avatar_thread_topico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="signature",
            field=models.TextField(default=None, null=True),
        ),
    ]
