# Generated by Django 4.2.5 on 2023-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_user_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="latest_update",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
