# Generated by Django 4.2.5 on 2023-10-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_reports_action_alter_reports_mod_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thread",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
