# Generated by Django 4.2.5 on 2023-10-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_post_is_removed_thread_is_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postemotes",
            name="emote",
            field=models.CharField(
                choices=[
                    (":thumbs_up:", "Like"),
                    (":thumbs_down:", "Dislike"),
                    (":red_heart:", "Love"),
                    (":warning:", "Warning"),
                    (":party_popper:", "Party"),
                    (":eyes:", "Eyes"),
                    (":confused_face:", "Sad"),
                    (":face_with_rolling_eyes:", "Rolling Eyes"),
                ],
                max_length=24,
            ),
        ),
        migrations.DeleteModel(
            name="Emotes",
        ),
    ]
