# Generated by Django 4.2.5 on 2023-10-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_postemotes_emote_delete_emotes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_timed_out",
        ),
        migrations.AddField(
            model_name="thread",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
